add_newline = false

[character]
error_symbol = "[✗](red)"
success_symbol = "[➜](green)"

[cmd_duration]
format = "took [$duration]($style)"
min_time = 0

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "
truncation_length = 2
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
format = "\\([$branch]($style)\\) "

[git_commit]
disabled = true

[hostname]
format = "at [$hostname]($style) "
ssh_only = false

[memory_usage]
disabled = false

[package]
disabled = true

[username]
format = "[#](blue) [$user]($style) "
show_always = true
